- name: Ensure Stow is installed
  community.general.homebrew:
    name: stow
    state: present

- name: stow dotfiles
  command: "stow -v -R -t ~ {{ item }}"
  args:
    chdir: "{{ playbook_dir }}/../dotfiles"
  loop: "{{ stow_packages }}"
