- name: Configure mac environment
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/all.yml

  roles:
    - dirs
    - homebrew
    - casks
    - fonts
    - macos_defaults
    - stow
